# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifierqualif',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Abbreviation'),
        ),
    ]
