# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_identifierqualif_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifier',
            name='abbreviation',
            field=models.ManyToManyField(to='term.IdentifierQualif', verbose_name='Abbreviation'),
        ),
    ]
