# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0003_identifier_abbreviation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identifierqualif',
            options={'ordering': ('abbreviation',)},
        ),
    ]
