# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesaurus_name', models.CharField(max_length=250, verbose_name='Thesaurus name')),
                ('thesaurus_author', models.CharField(max_length=250, verbose_name='Author')),
                ('thesaurus_scope', models.CharField(max_length=250, verbose_name='Scope')),
            ],
            options={
                'verbose_name': 'Thesaurus',
                'verbose_name_plural': 'Thesaurus',
            },
        ),
    ]
