# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thesaurus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(blank=True, choices=[('eng', 'English'), ('spa_la', 'Spanish Latin America'), ('por', 'Portuguese'), ('spa_es', 'Spanish Spain'), ('fre', 'French')], max_length=10, verbose_name='Language used for description')),
                ('descriptor_class', models.CharField(blank=True, choices=[('1', '1 - Topical Descriptor'), ('2', '2 - Publication Types, for example Review'), ('3', '3 - Check Tag, e.g., Male - no tree number'), ('4', '4 - Geographic Descriptor')], max_length=2, verbose_name='Descriptor class')),
                ('descriptor_name', models.CharField(max_length=250, verbose_name='Term name')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Date created')),
                ('date_revised', models.DateField(blank=True, null=True, verbose_name='Date revised')),
                ('date_established', models.DateField(blank=True, null=True, verbose_name='Date established')),
                ('annotation', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Annotation')),
                ('history_note', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Annotation')),
                ('nlm_class_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='NLM classification number')),
                ('online_note', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Online note')),
                ('public_mesh_note', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Public MeSH note')),
                ('consider_also', models.CharField(blank=True, max_length=250, null=True, verbose_name='Consider also')),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_ui', models.CharField(blank=True, max_length=250, null=True, verbose_name='MESH code')),
                ('decs_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='DeCS code')),
                ('thesaurus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='thesaurus.Thesaurus')),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registers',
            },
        ),
        migrations.CreateModel(
            name='PreviousIndexingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_indexing', models.CharField(blank=True, max_length=250, null=True, verbose_name='Previous indexing')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Identifier')),
            ],
            options={
                'verbose_name': 'Previous Indexing',
                'verbose_name_plural': 'Previous Indexing',
            },
        ),
        migrations.CreateModel(
            name='TreeNumbersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tree number')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Identifier')),
            ],
            options={
                'verbose_name': 'Tree number for descriptor',
                'verbose_name_plural': 'Tree numbers for descriptors',
            },
        ),
        migrations.AddField(
            model_name='description',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Identifier'),
        ),
    ]
