# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='thesaurus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='thesaurus.Thesaurus'),
        ),
    ]
