# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_auto_20171016_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousIndexingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_indexing', models.CharField(blank=True, max_length=250, null=True, verbose_name='Previous indexing')),
            ],
            options={
                'verbose_name': 'Previous Indexing',
                'verbose_name_plural': 'Previous Indexing',
            },
        ),
        migrations.CreateModel(
            name='TreeNumbersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tree number')),
            ],
            options={
                'verbose_name': 'Tree number for descriptor',
                'verbose_name_plural': 'Tree numbers for descriptors',
            },
        ),
        migrations.RemoveField(
            model_name='previousindexing',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='treenumbers',
            name='identifier',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='term_name',
            new_name='descriptor_name',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='description_language',
            new_name='language_code',
        ),
        migrations.RenameField(
            model_name='identifier',
            old_name='mesh_code',
            new_name='descriptor_ui',
        ),
        migrations.RemoveField(
            model_name='description',
            name='scope_note',
        ),
        migrations.AddField(
            model_name='description',
            name='consider_also',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Consider also'),
        ),
        migrations.AddField(
            model_name='description',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='description',
            name='date_established',
            field=models.DateField(blank=True, null=True, verbose_name='Date established'),
        ),
        migrations.AddField(
            model_name='description',
            name='date_revised',
            field=models.DateField(blank=True, null=True, verbose_name='Date revised'),
        ),
        migrations.AddField(
            model_name='description',
            name='descriptor_class',
            field=models.IntegerField(blank=True, choices=[('1', '1 - Topical Descriptor'), ('2', '2 - Publication Types, for example Review'), ('3', '3 - Check Tag, e.g., Male - no tree number'), ('4', '4 - Geographic Descriptor')], default='', verbose_name='Descriptor class'),
        ),
        migrations.AddField(
            model_name='description',
            name='nlm_class_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='NLM classification number'),
        ),
        migrations.AlterField(
            model_name='description',
            name='history_note',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Annotation'),
        ),
        migrations.DeleteModel(
            name='PreviousIndexing',
        ),
        migrations.DeleteModel(
            name='TreeNumbers',
        ),
        migrations.AddField(
            model_name='treenumberslist',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Identifier'),
        ),
        migrations.AddField(
            model_name='previousindexinglist',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.Identifier'),
        ),
    ]
