# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0004_auto_20171017_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='descriptor_class',
            field=models.CharField(blank=True, choices=[('1', '1 - Topical Descriptor'), ('2', '2 - Publication Types, for example Review'), ('3', '3 - Check Tag, e.g., Male - no tree number'), ('4', '4 - Geographic Descriptor')], max_length=2, verbose_name='Descriptor class'),
        ),
    ]
