# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0006_auto_20171017_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='descriptor_class',
        ),
    ]
