# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0007_remove_description_descriptor_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='description',
            name='date_established',
        ),
        migrations.RemoveField(
            model_name='description',
            name='date_revised',
        ),
        migrations.AddField(
            model_name='description',
            name='descriptor_class',
            field=models.CharField(blank=True, choices=[('1', '1 - Topical Descriptor'), ('2', '2 - Publication Types, for example Review'), ('3', '3 - Check Tag, e.g., Male - no tree number'), ('4', '4 - Geographic Descriptor')], max_length=2, verbose_name='Descriptor class'),
        ),
        migrations.AlterField(
            model_name='description',
            name='language_code',
            field=models.CharField(blank=True, choices=[('eng', 'English'), ('spa_la', 'Spanish Latin America'), ('por', 'Portuguese'), ('spa_es', 'Spanish Spain'), ('fre', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
    ]
