# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0008_auto_20171017_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='description',
            name='date_established',
            field=models.DateField(blank=True, null=True, verbose_name='Date established'),
        ),
        migrations.AddField(
            model_name='description',
            name='date_revised',
            field=models.DateField(blank=True, null=True, verbose_name='Date revised'),
        ),
    ]
